name: Update Redirect URIs

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update-redirect-uris:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Run update script
        run: node scripts/updateRedirectUris.ts
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          VERCEL_URL: ${{ secrets.VERCEL_URL }}
          VERCEL_BRANCH_URL: ${{ secrets.VERCEL_BRANCH_URL }}
